project: Add debian packaging metadata
endlessm/force-quit-dialog-extension pull request #2
Opened 2024-03-01 21:07 UTC by dylanmccall

This is copied from OBS, with the following changes:

- Removed two patches, which were applying changes that are already in this version of the source.
- Changed maintainer, homepage, etc. to something more useful.

https://phabricator.endlessm.com/T35079

2024-03-01 21:45 UTC, wjt requested changes

2024-03-01 21:45 UTC, wjt commented on debian/control
> +Uploaders: Dylan McCall <dylan@endlessos.org>
I often use:

```suggestion
Maintainer: Endless OS Maintainers <maintainers@endlessos.org>
```

2024-03-01 21:45 UTC, wjt commented on debian/control
> + gnome-shell (>= 3.37.90)
```suggestion
 gnome-shell (>= 43)
```

2024-03-01 21:45 UTC, wjt commented on debian/copyright
> +Source: https://gitlab.gnome.org/feaneron/force-quit-dialog-extension
Georges archived that repo: This is the upstream now.

2024-03-01 21:45 UTC, wjt commented on debian/copyright
> +Copyright: 2020 Georges Basile Stavracas Neto <georges@endlessm.com>
```suggestion
Copyright: 2020–2024 Endless OS Foundation LLC
```

2024-03-01 22:53 UTC, dylanmccall commented
Thanks for the review! I corrected those details :)

2024-03-04 10:08 UTC, wjt commented
retest this please

2024-03-04 10:11 UTC, wjt commented
```
+ dch -v 0+dev20.639a38a -D master --force-distribution 'Automatic release from git (0+dev20.639a38a)'
dch: fatal error at line 1219:
New version specified (0+dev20.639a38a) is less than
the current version number (3.38.0-1endless1)!  Use -b to force.
```

You need a `Version_XXXX` tag

2024-03-04 11:46 UTC, wjt commented
Looks good once you it builds.

2024-03-04 19:29 UTC, dylanmccall commented
:+1: I added a new release with the appropriate tag. Looks like it's working now :)

2024-03-04 19:31 UTC, merged

2024-03-04 19:44 UTC, dylanmccall commented
Oh, I was expecting that to fastforward, but somehow not :/ That's why there's one more build failure on master, but all sorted now.